### ISSUE TITLE
Can not connect  irFFB to SimHub

### ISSUE THREAD

**Issue by wirefri** [thogue95/irFFB#13]
Hello guys
I can not connect  irFFB to SimHub

SimHub  V8.2.1.: succesfully installed
irFFB 2022: succesfully installed
Toms.irFFB2022Connector.dll: succesfully installed
Toms.irFFB Dash.zip: succesfully installed
Toms.irFFB Status.zip: succesfully installed

Binding max force to Button of my Fanatec steeringwheel: succesfully installed

Problems:
irFFB tells me that simHub ist not installed and SimHub Connector Status is not active

What i have tried to do:
When you completed binding actions to keys or buttons, you can see the sliders on the irFFB2022 screen change as you press the relevant button or key that you bound that control: Does not work

Due to the timing of when irFFB2022 and SimHub are started, you will need to press of one of buttons/keys a few times initially to establish the connection between SimHub and irFFB2022. You will find it reliable after the communication is established:  Does not work

Any ideas why and how I can fix it? 
thanks!
René Widmer, Switzerland

**Comment by thogue95** [comment]
Sounds like you have installed in a different directory.  Toms.irFFB2022Connector.dll file must be located in the  C:\Program Files (x86)\SimHub directory.
