### ISSUE TITLE
"Use 360HZ telemetry for suspension effects in Game FFB modes" is greyed out and unchecked...

### ISSUE THREAD

**Issue by djkeithers** [thogue95/irFFB#14]
Is there any way to fix this and does having this box checked improved irffb2022?  I'm on a DD1.  Also when I try the Auto FFB switch speed mode, I lose FFB completely.   Am I supposed to set the switch speed MPH to a certain number?

Lastly what is the optimal setting for "effect timing"  I'm not quite sure what that setting does...

Thank you!

**Comment by thogue95** [comment]
Find me on the Busters Corner Discord Channel to see if we can get your problem resolved.

https://discord.com/invite/ACmxhCu9nf
