### ISSUE TITLE
irFFB Connector

### ISSUE THREAD

**Issue by reid2882** [thogue95/irFFB#16]
sim hub reports: 
irffb connector: No or Invalid data

**Comment by thogue95** [comment]
This happens when the irFFB Connector can not read the data from irFFB2022.  Do you have irFFB2022 running?

**Comment by reid2882** [comment]
yes

**Comment by thogue95** [comment]
You are not giving me enough context to help.  Join the Busters Corner Discord and find me there and we can see if we can resolve the issue.

https://discord.gg/aAfQfGDz
