### ISSUE TITLE
Addition of new cars

### ISSUE THREAD

**Issue by oldsim** [thogue95/irFFB#2]
Tom,

I have used the original irffb for about a year. When I come across a car that is not included in the intial list I've had to modify their list then recompile the program each time.

I recently saw a FB post from Busters Corner that indicated that your version of irffb will work with all cars, regardless of whether they are in the original list.  Further, your version will automatically retain the unique settings for each car/track combination.

Are these enhancememts included in your version?

**Comment by thogue95** [comment]
The enhancement I made works for any car so the car table is no longer relevant.

**Comment by oldsim** [comment]
Great improvememt!  Thanks
